namespace DsInApex.Core.Localization;

/// <summary>
/// 全部界面文案字典。
///
/// ⚠️ 重要背景（2026-10-03 Spike 实测）：
/// 上游 <c>ApexSenseBridgeTray/Common/LocalizationManager.cs</c> **只有 English 与 French 两种语言，
/// 共 121 个唯一键，没有任何中文**。因此中文侧是**全新翻译**，不是"填第三份字典"。
///
/// 英文侧的改动：品牌名 <c>ApexSenseBridge</c> → <c>Ds in Apex</c>（逐条核对替换）。
///
/// 约定：
/// - 键名前缀 <c>Loc_</c>（沿用上游命名，便于与上游 XAML 对照）
/// - 占位符用 <c>{0}</c> / <c>{1}</c>，与 <c>LocalizationManager.Format()</c> 配套
/// - 含换行的文案在 C# 里用 <c>\n</c>，不要写成真实换行
/// </summary>
public static class Strings
{
    // ═══════════════════════════════════════════════════════════════
    //  简体中文
    // ═══════════════════════════════════════════════════════════════
    public static readonly IReadOnlyDictionary<string, string> ZhCN =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            // ── General & App ──
            ["Loc_AppName"]              = "Ds in Apex",
            ["Loc_AppSubtitle"]          = "DualSense \u2192 飞智 APEX 4 / APEX 5 桥接",
            ["Loc_AlreadyRunning"]       = "Ds in Apex 已在系统托盘中运行。",
            ["Loc_StartupError"]         = "启动错误：",
            ["Loc_Close"]                = "关闭",
            ["Loc_BtnClose"]             = "关闭",
            ["Loc_Hide"]                 = "隐藏",
            ["Loc_Cancel"]               = "取消",
            ["Loc_Warning"]              = "警告",
            ["Loc_Confirm"]              = "确定",

            // ── Tray & Notifications ──
            ["Loc_TrayStatusStandby"]    = "Ds in Apex：待机",
            ["Loc_TrayStatusActive"]     = "Ds in Apex：{0}",
            ["Loc_TrayTooltipStandby"]   = "Ds in Apex - 待机",
            ["Loc_TrayOpen"]             = "打开界面...",
            ["Loc_TrayAutoDetect"]       = "自动检测",
            ["Loc_TrayCheckUpdates"]     = "检查更新...",
            ["Loc_TrayControlPanel"]     = "控制面板...",
            ["Loc_TrayLanguage"]         = "语言",
            ["Loc_TrayExit"]             = "退出",
            ["Loc_NotificationActivated"] = "Ds in Apex 已激活",
            ["Loc_NotificationGameProfile"] = "{0}\n配置档：{1}",
            ["Loc_NotificationGame"]     = "游戏",
            ["Loc_NotificationProfileStandard"] = "标准",
            ["Loc_NotificationWarning"]  = "Ds in Apex \u2014 警告",

            // ── Status Card ──
            ["Loc_StatusBadgeStandby"]   = "\u25cf 待机",
            ["Loc_StatusBadgeActive"]    = "\u25cf 桥接已激活",
            ["Loc_NoActiveGame"]         = "无活动游戏",
            ["Loc_WaitingHint"]          = "等待兼容游戏启动...",
            ["Loc_ProfileStandard"]      = "标准",
            ["Loc_ProfileRemapping"]     = "重映射已启用",
            ["Loc_PillTriggers"]         = "扳机",
            ["Loc_PillHaptics"]          = "触觉",
            ["Loc_BtnExcludeCurrent"]    = "排除此游戏",
            ["Loc_MsgExcluded"]          = "\u201c{0}\u201d 已从自动检测中排除。",
            ["Loc_ManualBridgeGameTitle"] = "强制手动桥接",

            // ── Auto Detect Section ──
            ["Loc_SectionAutoDetect"]    = "自动检测",
            ["Loc_EnableDetection"]      = "启用检测",
            ["Loc_EnableDetectionHint"]  = "兼容游戏启动时自动激活桥接",
            ["Loc_LaunchCriteria"]       = "仅在以下情况启动桥接：",
            ["Loc_CriteriaAdaptive"]     = "支持自适应扳机的游戏",
            ["Loc_CriteriaHaptic"]       = "支持触觉反馈的游戏",

            // ── Configuration Section ──
            ["Loc_SectionConfig"]        = "配置",
            ["Loc_Notifications"]        = "通知",
            ["Loc_NotificationsHint"]    = "桥接激活时显示 Windows 通知",
            ["Loc_ManualBridge"]         = "强制持续激活",
            ["Loc_ManualBridgeHint"]     = "无需等待游戏，持续保持桥接激活",
            ["Loc_Language"]             = "语言",
            ["Loc_LanguageHint"]         = "界面显示语言",
            ["Loc_SoftwareUpdate"]       = "软件更新",
            ["Loc_BtnCheck"]             = "检查",

            // ── Update Banner ──
            ["Loc_UpdateBannerTitle"]    = "有可用更新！",
            ["Loc_UpdateBannerSubtitle"] = "新版本已准备好下载",
            ["Loc_BtnDownload"]          = "下载",
            ["Loc_UpdateAvailableNotification"] = "有可用更新",
            ["Loc_UpdateAvailableBody"]  = "Ds in Apex v{0} 已发布。",
            ["Loc_UpdateDialogTitle"]    = "Ds in Apex \u2014 更新",
            ["Loc_UpdateDialogAvailableTitle"] = "Ds in Apex \u2014 有可用更新",
            ["Loc_UpdatePrompt"]         = "Ds in Apex 有新版本可用！\n\n当前版本：v{0}\n最新版本：v{1}\n\n是否立即下载？",
            ["Loc_UpdateUpToDate"]       = "Ds in Apex 已是最新版本（v{0}）。",
            ["Loc_UpdateError"]          = "检查更新时出错：",
            ["Loc_UpdateCheckUnavailable"] = "当前无法检查更新。\n请检查网络连接。",

            // ── Database Section ──
            ["Loc_DatabaseTitle"]        = "PCGamingWiki 数据库",
            ["Loc_CertifiedGamesSingular"] = "{0} 款认证游戏",
            ["Loc_CertifiedGamesPlural"] = "{0} 款认证游戏",
            ["Loc_BtnGameList"]          = "游戏列表",
            ["Loc_BtnLearnedExecutables"] = "已学习",
            ["Loc_BtnSync"]              = "同步",
            ["Loc_Syncing"]              = "正在同步...",
            ["Loc_SyncSuccess"]          = "更新成功！\n{0} {1}。",
            ["Loc_SyncSuccessGamesSingular"] = "款兼容游戏已载入",
            ["Loc_SyncSuccessGamesPlural"] = "款兼容游戏已载入",
            ["Loc_SyncFailed"]           = "无法下载最新列表。\n请检查网络连接。",
            ["Loc_LearnedWindowTitle"]   = "已学习的可执行文件",
            ["Loc_LearnedWindowHint"]    = "当游戏进程稳定保持 30 秒后完成验证，强制手动桥接期间的被动识别同样计入。导出内容永不含本地路径。",
            ["Loc_LearnedGame"]          = "游戏",
            ["Loc_LearnedExecutable"]    = "可执行文件",
            ["Loc_LearnedMethod"]        = "检测方式",
            ["Loc_LearnedSessions"]      = "会话数",
            ["Loc_LearnedLastSeen"]      = "最近出现",
            ["Loc_LearnedEmpty"]         = "尚未学习到任何可执行文件。",
            ["Loc_LearnedCountSingular"] = "已学习 {0} 个可执行文件",
            ["Loc_LearnedCountPlural"]   = "已学习 {0} 个可执行文件",
            ["Loc_LearningPendingSingular"] = "{0} 项验证进行中",
            ["Loc_LearningPendingPlural"] = "{0} 项验证进行中",
            ["Loc_BtnSelectAll"]         = "全选",
            ["Loc_BtnDeleteLearned"]     = "删除",
            ["Loc_BtnExportLearned"]     = "导出",
            ["Loc_LearnedDeleteConfirm"] = "删除选中的已学习关联（{0} 项）？",
            ["Loc_LearnedExportSuccess"] = "所选关联已导出，不含本地路径。",
            ["Loc_LearnedExportFailed"]  = "导出失败：{0}",

            // ── Footer ──
            ["Loc_FooterStatus"]         = "Ds in Apex 正在后台运行",
            ["Loc_BtnHide"]              = "隐藏",

            // ── Game List Window ──
            ["Loc_GameListTitle"]        = "Ds in Apex \u2014 兼容游戏",
            ["Loc_GameListSubtitle"]     = "浏览认证游戏并管理自动排除项",
            ["Loc_SearchPlaceholder"]    = "搜索游戏...",
            ["Loc_TabAll"]               = "全部",
            ["Loc_TabTriggers"]          = "自适应扳机",
            ["Loc_TabHaptics"]           = "触觉反馈",
            ["Loc_TabExcluded"]          = "已排除",
            ["Loc_GamesDisplayedSingular"] = "已显示 {0} 款游戏",
            ["Loc_GamesDisplayedPlural"] = "已显示 {0} 款游戏",
            ["Loc_GamesExcludedSingular"] = "已排除 {0} 款",
            ["Loc_GamesExcludedPlural"]  = "已排除 {0} 款",
            ["Loc_PillAdaptive"]         = "自适应扳机",
            ["Loc_PillHaptic"]           = "触觉反馈",
            ["Loc_PillTouchpad"]         = "触摸板重映射",
            ["Loc_ApexProfile"]          = "APEX 配置档",
            ["Loc_ApexProfileKeep"]      = "保持当前",
            ["Loc_ApexProfileNumber"]    = "配置档 {0}",
            ["Loc_ApexProfileHint"]      = "游戏运行期间临时切换到该板载配置档，退出后恢复原配置档。",
            ["Loc_StateIncluded"]        = "已包含",
            ["Loc_StateExcluded"]        = "已排除",
            ["Loc_ExclusionsSavedHint"]  = "排除项与游戏配置档会自动保存。",
            ["Loc_NavCertifiedGames"]    = "认证游戏",
            ["NavLearnedExecutables"]    = "已学习的可执行文件",
            ["Loc_NavLearnedExecutables"] = "已学习的可执行文件",
            ["Loc_LearnedSubtitle"]      = "本机与兼容游戏关联的可执行文件",
            ["Loc_LearnedSearchPlaceholder"] = "搜索可执行文件或游戏...",
            ["Loc_LearnedEmptySubtitle"] = "当游戏以稳定会话运行时，其关联会出现在这里以便下次秒启动。",
            ["Loc_LearnedEmptyPendingSingular"] = "检测到一款游戏。请继续游玩，正在验证其可执行文件。",
            ["Loc_LearnedEmptyPendingPlural"] = "检测到 {0} 个游戏进程。请继续游玩，正在验证它们的可执行文件。",
            ["Loc_BtnDeleteSingle"]      = "删除",

            // ── 导航（DIA 新增，P1 八页面） ──
            ["Loc_NavDashboard"]         = "仪表盘",
            ["Loc_NavGameLibrary"]       = "游戏库",
            ["Loc_NavLearned"]           = "学习记录",
            ["Loc_NavDrivers"]           = "驱动管理",
            ["Loc_NavHardwareTest"]      = "硬件测试",
            ["Loc_NavDiagnostics"]       = "诊断",
            ["Loc_NavSettings"]          = "设置",
            ["Loc_NavAbout"]             = "关于",

            // ── 页面占位副标题（P1 空壳用，P2+ 逐步替换为真实内容） ──
            ["Loc_PageDashboardDesc"]    = "桥接状态、当前游戏与快捷操作",
            ["Loc_PageGameLibraryDesc"]  = "浏览认证游戏并管理排除项与配置档绑定",
            ["Loc_PageLearnedDesc"]      = "已识别的可执行文件与其会话记录",
            ["Loc_PageDriversDesc"]      = "USBip / HidHide / ViGEmBus 驱动状态与安装",
            ["Loc_PageHardwareDesc"]     = "设备识别、扳机与震动测试、输入监视",
            ["Loc_PageDiagnosticsDesc"]  = "一键收集诊断信息并导出报告",
            ["Loc_PageSettingsDesc"]     = "检测策略、通知、语言与更新",
            ["Loc_PageAboutDesc"]        = "版本信息、开源许可与项目说明",

            // ── 占位提示 ──
            ["Loc_PlaceholderPending"]   = "此页面将在后续阶段实现。",

            // ══════════════ P2 新增 · 桥接会话（BridgeSession / EngineSessionManager） ══════════════
            // 上游这类文案全是法语硬编码，DIA 全部改为字典键。
            ["Loc_None"]                     = "无",
            ["Loc_ErrBridgeIpcCollision"]    = "IPC 事件名冲突。",
            ["Loc_ErrBridgeStartFailed"]     = "无法启动 Ds in Apex 桥接：",
            ["Loc_ErrBridgeProcessNotStarted"] = "桥接进程未能启动。",
            ["Loc_ErrBridgeStopFailed"]      = "停止桥接会话失败：",
            ["Loc_ErrBridgeExited"]          = "桥接在报告就绪前就退出了（代码 {0}）。",
            ["Loc_ErrBridgeInitTimeout"]     = "桥接未能在 {0} 秒内完成初始化。",
            ["Loc_ErrBridgeIpcIncompatible"] = "桥接返回了不兼容的 IPC 状态。",
            ["Loc_ErrBridgeInitFailed"]      = "桥接初始化失败（代码 {0}）。",
            ["Loc_ErrBridgeStartFailedShort"] = "桥接启动失败。",
            ["Loc_ErrSessionAlreadyActive"]  = "已有一个会话处于活动或初始化中。",
            ["Loc_ErrExternalSessionActive"] = "已有一个由 Playnite 或其他程序管理的桥接会话处于活动状态。",
            ["Loc_ErrExternalSessionActiveHint"] = "本程序不会干扰该会话。",
            ["Loc_ErrEngineNotFound"]        = "找不到 ApexSenseBridge.exe，请安装或修复 Ds in Apex。",
            ["Loc_LogStartingBridge"]        = "正在启动桥接：{0} {1}",
            ["Loc_LogStoppingSession"]       = "正在停止会话：{0}",

            // ── 会话阶段 ──
            ["Loc_PhaseEmpty"]               = "空闲",
            ["Loc_PhaseStarting"]            = "正在启动",
            ["Loc_PhaseReady"]               = "就绪",
            ["Loc_PhaseStopping"]            = "正在停止",
            ["Loc_PhaseStopped"]             = "已停止",
            ["Loc_PhaseFailed"]              = "失败",

            // ── 仪表盘（P2） ──
            ["Loc_SectionBridge"]            = "桥接",
            ["Loc_QuickActions"]             = "快捷操作",
            ["Loc_BtnStartBridge"]           = "启动桥接",
            ["Loc_BtnStopBridge"]            = "停止桥接",
            ["Loc_BtnOpenSettings"]          = "打开设置",
            ["Loc_BridgeState"]              = "状态",
            ["Loc_BridgePid"]                = "进程 ID",
            ["Loc_EnginePath"]               = "引擎路径",
            ["Loc_EngineMissing"]            = "未找到引擎可执行文件",
            ["Loc_EngineRescan"]             = "重新定位",

            // ── 设置页（P2） ──
            ["Loc_HapticThreshold"]          = "触觉阈值",
            ["Loc_HapticThresholdHint"]      = "低于该强度的音频触觉事件将被忽略（0–95）",
            ["Loc_InitTimeout"]              = "初始化超时",
            ["Loc_InitTimeoutHint"]          = "等待桥接就绪的秒数（5–120）",
            ["Loc_SectionAppearance"]        = "外观",
            ["Loc_Theme"]                    = "主题",
            ["Loc_ThemeHint"]                = "界面配色方案",
            ["Loc_ThemeSystem"]              = "跟随系统",
            ["Loc_ThemeLight"]               = "浅色",
            ["Loc_ThemeDark"]                = "深色",
            ["Loc_AutoSaveHint"]             = "所有设置修改会立即保存。",

            // ── Game Library（P3） ──
            ["Loc_GamesSearchPlaceholder"]   = "搜索游戏名或配置档…",
            ["Loc_GamesFilterAll"]           = "全部游戏",
            ["Loc_GamesFilterAdaptive"]      = "仅自适应扳机",
            ["Loc_GamesFilterHaptic"]        = "仅触觉反馈",
            ["Loc_GamesFilterExcluded"]      = "已排除",
            ["Loc_GamesSortTitle"]           = "按名称排序",
            ["Loc_GamesSortAppId"]           = "按 Steam AppID 排序",
            ["Loc_GamesSyncCloud"]           = "同步游戏库",
            ["Loc_GamesSyncing"]             = "正在同步…",
            ["Loc_GamesSyncOk"]              = "已同步：{0} 款游戏",
            ["Loc_GamesSyncFail"]            = "同步失败（已保留本地数据）",
            ["Loc_GamesShown"]               = "已显示 {0} 款",
            ["Loc_GamesExcludedCount"]       = "已排除 {0} 款",
            ["Loc_GamesExcludeToggle"]       = "排除",
            ["Loc_LegendAdaptive"]           = "自适应扳机",
            ["Loc_LegendHaptic"]             = "触觉反馈",
            ["Loc_LegendRemap"]              = "自定义映射",
            ["Loc_ApexProfileKeep"]          = "保持原样",
            ["Loc_ApexProfile1"]             = "APEX 配置档 1",
            ["Loc_ApexProfile2"]             = "APEX 配置档 2",
            ["Loc_ApexProfile3"]             = "APEX 配置档 3",
            ["Loc_ApexProfile4"]             = "APEX 配置档 4",

            // ── Learned Executables（P3） ──
            ["Loc_LearnedSearchPlaceholder"] = "搜索游戏名、可执行文件或路径…",
            ["Loc_LearnedCount"]             = "共 {0} 条学习记录",
            ["Loc_LearningPendingCount"]     = "{0} 条待验证",
            ["Loc_LearnedEmpty"]             = "还没有学习记录",
            ["Loc_LearnedEmptySubtitle"]     = "游戏被自动识别并稳定运行约 30 秒后，识别结果会记录在这里。",
            ["Loc_LearnedDeleteConfirm"]     = "确定删除选中的 {0} 条学习记录？此操作不可撤销。",
            ["Loc_LearnedExportSuccess"]     = "导出成功。",
            ["Loc_LearnedExportFailed"]      = "导出失败：{0}",
            ["Loc_BtnSelectAll"]             = "全选",
            ["Loc_BtnDeleteLearned"]         = "删除",
            ["Loc_BtnExportLearned"]         = "导出",
            ["Loc_BtnDelete"]                = "删除",

            // ── Driver Management（P4） ──
            ["Loc_Driver_usbip-win2"]        = "usbip-win2 驱动（USB 转发）",
            ["Loc_Driver_HidHide"]           = "HidHide（手柄隐藏）",
            ["Loc_Driver_ViGEmBus"]          = "ViGEmBus（可选）",
            ["Loc_DriverState_Running"]      = "已就绪",
            ["Loc_DriverState_Installed"]    = "已安装",
            ["Loc_DriverState_NotInstalled"] = "未安装",
            ["Loc_DriverState_Outdated"]     = "版本不符",
            ["Loc_DriverState_Partial"]      = "安装不完整",
            ["Loc_DriverState_OptionalMissing"] = "未安装（可选）",
            ["Loc_DriverState_Unknown"]      = "未知",
            ["Loc_DriverVersionExpected"]    = "需要版本 {0}",
            ["Loc_DriverVersionInstalled"]   = "已安装版本 {0}",
            ["Loc_DriverServices"]           = "服务：{0}",
            ["Loc_DriverInstallerVerified"]  = "捆绑安装器已通过 SHA-256 校验",
            ["Loc_DriverInstallerUnverified"] = "捆绑安装器校验未通过（文件可能损坏或被替换）",
            ["Loc_DriverInstallerMissing"]   = "找不到捆绑安装器",
            ["Loc_DriverInstallerNone"]      = "该组件无可捆绑安装器",
            ["Loc_DriversSummary"]           = "{0} 项就绪 / 共 {1} 项",
            ["Loc_DriversRefresh"]           = "重新检测",
            ["Loc_DriversInstall"]           = "安装",
            ["Loc_DriversRepair"]            = "修复",
            ["Loc_DriversInstalling"]        = "正在安装 {0}…（若弹出 UAC 请确认）",
            ["Loc_DriversInstallDone"]       = "安装完成。",
            ["Loc_DriversElevated"]          = "当前以管理员身份运行。",
            ["Loc_DriversNotElevated"]       = "安装 / 修复需要管理员权限，点击后会弹出 UAC 确认。",
            ["Loc_DriversNeedsRestart"]      = "有驱动已注册但尚未运行，可能需要重启 Windows 后生效。",
            ["Loc_DriversOptionalHint"]      = "可选组件：DIA 内置 libVIIPER，未安装不影响使用。",

            // ═══════════════ P5：硬件测试 + 诊断 ═══════════════
            // ── 连接方式 ──
            ["Loc_Link_Wired"]               = "有线",
            ["Loc_Link_Dongle"]              = "2.4G 接收器",
            ["Loc_Link_Bluetooth"]           = "蓝牙",
            ["Loc_Link_Unknown"]             = "未知",

            // ── 通用短词 ──
            ["Loc_HwYes"]                    = "是",
            ["Loc_HwNo"]                     = "否",
            ["Loc_HwNone"]                   = "无",
            ["Loc_HwCharging"]               = "充电中",
            ["Loc_HwLatest"]                 = "最新",

            // ── 状态条 ──
            ["Loc_HwEngineReady"]            = "引擎已就绪",
            ["Loc_HwEngineMissing"]          = "未找到引擎",
            ["Loc_HwSessionRunning"]         = "桥接会话运行中（硬件测试已锁定）",
            ["Loc_HwSessionIdle"]            = "桥接会话未运行",
            ["Loc_HwRefresh"]                = "重新识别设备",
            ["Loc_HwBusyListing"]            = "正在读取设备信息…",
            ["Loc_HwBusyRunning"]            = "正在执行 {0}…",

            // ── 设备卡 ──
            ["Loc_HwNoDevice"]               = "未检测到手柄",
            ["Loc_HwNoDeviceHint"]           = "请确认手柄已连接，并处于 DInput 模式（长按 FN + A 约 3 秒切换）。",
            ["Loc_HwDeviceDetail"]           = "VID:PID {0}:{1} · 输入 {2} 字节 / 输出 {3} 字节",
            ["Loc_HwIdentityDetail"]         = "代号 {0} · 固件 {1} · {2}",
            ["Loc_HwLegacyAlias"]            = "{0}（引擎识别名：{1}）",

            // ── 分区标题 ──
            ["Loc_HwSectionReadOnly"]        = "只读检测",
            ["Loc_HwSectionReadOnlyHint"]    = "这些命令只读取设备信息，不改变任何状态，可以随时执行。",
            ["Loc_HwSectionInput"]           = "输入监视",
            ["Loc_HwSectionInputHint"]       = "采样期间请推动摇杆、按下扳机与按键；结束后会显示引擎实际读到的取值范围。",
            ["Loc_HwSectionTest"]            = "硬件测试（会真实驱动手柄）",
            ["Loc_HwSectionTestHint"]        = "以下操作会真实驱动扳机或马达 —— 请握好手柄再点。桥接会话运行期间不可用。",
            ["Loc_HwSessionBlocksTest"]      = "桥接会话正在运行：测试命令与会话会争用同一个 HID 接口，请先停止桥接。",
            ["Loc_HwSectionEmergency"]       = "应急操作",
            ["Loc_HwSectionEmergencyHint"]   = "用于异常情况下的救场。这些操作会改变全局状态，或影响其他程序持有的会话。",
            ["Loc_HwSampleSeconds"]          = "采样秒数",
            ["Loc_HwRawOutput"]              = "原始输出",
            ["Loc_HwParseDegraded"]          = "引擎输出与预期格式不符，已降级显示原始文本：{0}",
            ["Loc_HwConfirmTitle"]           = "请确认",
            ["Loc_HwConfirmStopSessions"]    = "这会停止所有活动桥接会话，包括由 Playnite 插件或官方托盘启动的会话。确定继续？",
            ["Loc_HwConfirmRestoreVisibility"] = "这会恢复被隐藏的手柄可见性，并还原 APEX 配置档状态。确定继续？",

            // ── 按钮 ──
            ["Loc_HwBtnDiagnose"]            = "HID 接口诊断",
            ["Loc_HwBtnXInput"]              = "XInput 槽位",
            ["Loc_HwBtnDryRun"]              = "报文预览",
            ["Loc_HwBtnVirtualDs"]           = "虚拟 DS5 测试",
            ["Loc_HwBtnInputMonitor"]        = "开始监视",
            ["Loc_HwBtnTestRt"]              = "扳机测试（RT）",
            ["Loc_HwBtnTestRumble"]          = "震动测试",
            ["Loc_HwBtnPortTest"]            = "综合端口测试",
            ["Loc_HwBtnProfileSwitch"]       = "配置档切换测试",
            ["Loc_HwBtnClear"]               = "清空扳机与震动",
            ["Loc_HwBtnStopSessions"]        = "停止所有会话",
            ["Loc_HwBtnRestoreVisibility"]   = "恢复手柄可见性",

            // ── 结果标题 ──
            ["Loc_HwResultIdentify"]         = "设备身份",
            ["Loc_HwResultDiagnose"]         = "HID 接口诊断",
            ["Loc_HwResultInputStatus"]      = "输入监视结果",
            ["Loc_HwResultVirtualDs"]        = "虚拟 DualSense 结果",
            ["Loc_HwResultXInput"]           = "XInput 槽位",
            ["Loc_HwResultDryRun"]           = "测试报文预览",
            ["Loc_HwResultTestRt"]           = "扳机测试",
            ["Loc_HwResultTestRumble"]       = "震动测试",
            ["Loc_HwResultProfileSwitch"]    = "配置档切换测试",
            ["Loc_HwResultPortTest"]         = "综合端口测试",
            ["Loc_HwResultClear"]            = "清空效果",
            ["Loc_HwResultStopSessions"]     = "停止会话",
            ["Loc_HwResultRestoreVisibility"] = "恢复手柄可见性",

            // ── 结果字段 ──
            ["Loc_HwField_Conclusion"]       = "结论",
            ["Loc_HwField_InterfaceCount"]   = "HID 接口总数",
            ["Loc_HwField_Apex4Interfaces"]  = "APEX 4 厂商接口",
            ["Loc_HwField_XInputSlots"]      = "已连接槽位",
            ["Loc_HwField_Model"]            = "机型",
            ["Loc_HwField_Codename"]         = "代号",
            ["Loc_HwField_DeviceType"]       = "设备类型",
            ["Loc_HwField_Firmware"]         = "固件",
            ["Loc_HwField_Link"]             = "连接方式",
            ["Loc_HwField_Battery"]          = "电量",
            ["Loc_HwField_AdaptiveTriggers"] = "自适应扳机",
            ["Loc_HwField_Backend"]          = "后端",
            ["Loc_HwField_EventDriven"]      = "事件驱动",
            ["Loc_HwField_ReceivedState"]    = "收到状态",
            ["Loc_HwField_Reports"]          = "报文数",
            ["Loc_HwField_StateChanges"]     = "状态变化",
            ["Loc_HwField_Timeouts"]         = "超时",
            ["Loc_HwField_ParseFailures"]    = "解析失败",
            ["Loc_HwField_LeftStick"]        = "左摇杆 X, Y",
            ["Loc_HwField_RightStick"]       = "右摇杆 X, Y",
            ["Loc_HwField_Triggers"]         = "扳机 L2, R2",
            ["Loc_HwField_DPad"]             = "方向键（末次）",
            ["Loc_HwField_SeenDPad"]         = "方向键（采样期间）",
            ["Loc_HwField_Buttons"]          = "按键",
            ["Loc_HwField_Warning"]          = "警告",
            ["Loc_HwField_VirtualConnected"] = "虚拟 DS5 已连接",
            ["Loc_HwField_BackendVersion"]   = "后端版本",
            ["Loc_HwField_DsFirmware"]       = "DS5 固件",
            ["Loc_HwField_InputMode"]        = "输入模式",
            ["Loc_HwField_ApexRouting"]      = "APEX 路由",
            ["Loc_HwField_OutputReports"]    = "输出报告",
            ["Loc_HwField_TriggerReports"]   = "扳机报告",
            ["Loc_HwField_RumbleReports"]    = "震动报告",
            ["Loc_HwField_AudioHaptics"]     = "音频触觉帧",
            ["Loc_HwField_MalformedFrames"]  = "畸形帧",
            ["Loc_HwField_UnknownFrames"]    = "未知帧",

            // ── 成功结论 ──
            ["Loc_HwSummary_List"]           = "找到 {0} 个候选设备。",
            ["Loc_HwSummary_ListEmpty"]      = "没有找到 APEX 4/5 的厂商 HID 接口。",
            ["Loc_HwSummary_Identify"]       = "{0} · 固件 {1} · {2}",
            ["Loc_HwSummary_Diagnose"]       = "枚举到 {0} 个 HID 接口，其中 APEX 4 厂商接口 {1} 个。",
            ["Loc_HwSummary_InputStatus"]    = "采样期间收到 {0} 份报文、{1} 次状态变化、{2} 次超时。",
            ["Loc_HwSummary_VirtualDs"]      = "虚拟 DualSense 已创建并收到反馈（后端 {0}）。",
            ["Loc_HwSummary_XInput"]         = "已连接的 XInput 槽位：{0}",
            ["Loc_HwSummary_XInputNone"]     = "系统未检测到 XInput 设备。",
            ["Loc_HwSummary_TestRt"]         = "扳机测试完成，结束后已自动复位。",
            ["Loc_HwSummary_TestRumble"]     = "震动测试完成，马达已停止。",
            ["Loc_HwSummary_ProfileSwitch"]  = "配置档切换测试完成，原配置档已恢复。",
            ["Loc_HwSummary_PortTest"]       = "综合端口测试完成。",
            ["Loc_HwSummary_Clear"]          = "LT / RT 已复位为 Normal，握把震动已停止。",
            ["Loc_HwSummary_DryRun"]         = "已生成测试报文（未做任何 HID 写入）。",
            ["Loc_HwSummary_StopSessions"]   = "已停止所有活动会话，虚拟输入 / 手柄可见性 / 配置档均已清理。",
            ["Loc_HwSummary_RestoreVisibility"] = "手柄可见性与 APEX 配置档状态已恢复。",
            ["Loc_HwSummary_Generic"]        = "命令执行成功。",

            // ── 阻断与错误 ──
            ["Loc_HwUnknownCommand"]         = "未知命令：{0}",
            ["Loc_HwBlockedBySession"]       = "桥接会话正在运行；测试命令需要独占手柄，请先停止桥接。",
            ["Loc_HwTimedOut"]               = "命令超时（超过 {0} 秒）已被中止。",
            ["Loc_HwRetriedNotice"]          = "（首次尝试因设备占用失败，已自动重试一次）",

            // ── 引擎退出码语义 ──
            ["Loc_HwExit_Ok"]                = "命令执行成功。",
            ["Loc_HwExit_NoDevice"]          = "没有找到 APEX 4/5 的厂商 HID 接口 —— 请确认手柄已连接、且处于 DInput 模式。",
            ["Loc_HwExit_IdentityFailed"]    = "身份校验失败 —— 设备可能被 Flydigi Space Station 等程序占用。",
            ["Loc_HwExit_InputStreamFailed"] = "输入流中断 —— 手柄可能在采样期间断开。",
            ["Loc_HwExit_NoState"]           = "采样期间没有收到任何输入状态。",
            ["Loc_HwExit_OpenFailed"]        = "无法打开手柄。",
            ["Loc_HwExit_WriteFailed"]       = "写入扳机效果失败。",
            ["Loc_HwExit_ResetFailed"]       = "测试后自动复位失败 —— 请在飞智空间站把手柄两个扳机设回「标准」。",
            ["Loc_HwExit_RumbleFailed"]      = "震动写入或停止失败。",
            ["Loc_HwExit_Apex5Only"]         = "该命令仅支持 APEX 5；当前机型不适用，未发送任何命令。",
            ["Loc_HwExit_Apex4Only"]         = "该命令需要已验证的 APEX 4；当前机型不匹配。",
            ["Loc_HwExit_ProfilePreflight"]  = "切换前的配置档状态预检失败。",
            ["Loc_HwExit_ProfileSwitchUnverified"] = "配置档切换未能验证，但原配置档已恢复。",
            ["Loc_HwExit_ProfileRestoreFailed"] = "原配置档未能恢复 —— 请用「恢复手柄可见性」应急操作，或用手柄快捷方式手动切回。",
            ["Loc_HwExit_ClearFailed"]       = "清除扳机 / 震动效果失败。",
            ["Loc_HwExit_StopSessionsFailed"] = "请求停止活动会话失败 —— 可能有更高权限的进程持有会话。",
            ["Loc_HwExit_RestoreVisibilityFailed"] = "恢复手柄可见性失败 —— 可能需要管理员权限。",
            ["Loc_HwExit_BadArguments"]      = "参数不被引擎接受（参数拼写或取值范围有误）。",
            ["Loc_HwExit_GenericFailure"]    = "命令失败（退出码 {0}，详见原始输出）。",

            // ── 诊断页 ──
            ["Loc_DiagCollecting"]           = "正在收集…",
            ["Loc_DiagSuccess"]              = "诊断包已生成",
            ["Loc_DiagFailed"]               = "收集失败",
            ["Loc_DiagArchivePath"]          = "{0}",
            ["Loc_DiagPartialKept"]          = "中间文件保留在：{0}",
            ["Loc_DiagOutputDir"]            = "输出目录",
            ["Loc_DiagOpenDir"]              = "打开目录",
            ["Loc_DiagSampleSeconds"]        = "XInput 采样秒数",
            ["Loc_DiagSkipSample"]           = "跳过交互式采样（仍会枚举 XInput 槽位）",
            ["Loc_DiagKeepWorking"]          = "保留未压缩的中间文件（便于排查）",
            ["Loc_DiagSafetyNote"]           = "收集全程只读：不安装驱动、不修改手柄设置、不发送任何效果或输出报文。报告不含用户名与计算机名。",
            ["Loc_DiagBtnCollect"]           = "收集诊断并导出 ZIP",
            ["Loc_DiagBtnCancel"]            = "中止",
            ["Loc_DiagRevealArchive"]        = "在资源管理器中显示",
            ["Loc_DiagWarningsTitle"]        = "收集过程中发现以下警告：",
            ["Loc_DiagLog"]                  = "收集日志",
            ["Loc_DiagStep_system"]          = "系统信息",
            ["Loc_DiagStep_hid"]             = "HID 接口",
            ["Loc_DiagStep_pnp"]             = "即插即用拓扑",
            ["Loc_DiagStep_xinput"]          = "XInput",
            ["Loc_DiagStep_software"]        = "冲突软件",
            ["Loc_DiagStep_archive"]         = "打包",

            // ══════════════ P6 新增 · 托盘后台 / 开机自启 / 便携部署 / 恢复状态 ══════════════

            // ── 托盘菜单 ──
            ["Loc_TrayStatusLabel"]           = "状态",
            ["Loc_TrayDiagnostics"]           = "诊断面板...",
            ["Loc_TrayHardwareTest"]          = "硬件测试...",
            ["Loc_TrayStartWithWindows"]      = "开机自启",
            ["Loc_TrayPortableInfo"]          = "便携版信息...",
            ["Loc_TrayRecoveryRestore"]       = "恢复手柄可见性",
            ["Loc_TrayRecoveryPending"]       = "⚠ 上次会话异常遗留（点击恢复）",

            // ── 托盘气泡通知（走 Shell_NotifyIcon，不用 Toast —— 见 §5.6） ──
            ["Loc_NotifyBridgeStartedTitle"]  = "桥接已启动",
            ["Loc_NotifyBridgeStartedBody"]   = "{0}\n配置档：{1}",
            ["Loc_NotifyBridgeStoppedTitle"]  = "桥接已停止",
            ["Loc_NotifyBridgeStoppedBody"]   = "原因：{0}",
            ["Loc_NotifyBridgeErrorTitle"]    = "桥接出错",
            ["Loc_NotifyMinimizedTitle"]      = "仍在后台运行",
            ["Loc_NotifyMinimizedBody"]       = "窗口已隐藏到托盘，桥接继续工作。退出请用托盘菜单。",
            ["Loc_NotifyUpdateTitle"]         = "有可用更新",
            ["Loc_NotifyUpdateBody"]          = "当前 v{0} → 最新 v{1}",
            ["Loc_NotifyRecoveryTitle"]       = "手柄恢复提醒",
            ["Loc_NotifyRecoveryBody"]        = "检测到上次会话异常遗留，手柄可能仍对系统隐藏。",

            // ── 设置页 · 启动与后台 ──
            ["Loc_SectionStartup"]            = "启动与后台",
            ["Loc_StartWithWindows"]          = "开机自启",
            ["Loc_StartWithWindowsHint"]      = "登录 Windows 后自动启动并最小化到托盘（写入当前用户注册表，不需要管理员）",
            ["Loc_StartWithWindowsStaleTitle"] = "自启路径已失效",
            ["Loc_StartWithWindowsStale"]     = "自启项指向的是另一个位置的程序，当前设置不会生效。便携版移动目录后必然出现这种情况。",
            ["Loc_StartWithWindowsRepair"]    = "修复为当前路径",
            ["Loc_StartWithWindowsUnreadable"] = "自启项读取失败：{0}",
            ["Loc_CloseToTray"]               = "关闭窗口时隐藏到托盘",
            ["Loc_CloseToTrayHint"]           = "点 X 不结束程序，桥接在后台继续工作；彻底退出请用托盘菜单的「退出」",
            ["Loc_CheckUpdatesOnStartup"]     = "启动时检查更新",
            ["Loc_CheckUpdatesOnStartupHint"] = "静默检查，只有发现新版本时才提示",
            ["Loc_CheckNow"]                  = "立即检查更新",
            ["Loc_UpdateNoRelease"]           = "发布页尚无可下载版本（当前 v{0}）",
            ["Loc_UpdatePortableHint"]        = "便携版升级方式：下载新目录替换即可，用户数据与设置不受影响。",

            // ── 设置页 · 便携部署 ──
            ["Loc_PortableInfo"]              = "便携部署",
            ["Loc_PortableHint"]              = "解压即用：不写安装项、不注册系统服务；卸载 = 删除目录（用户数据需另行清理）。",
            ["Loc_PortableAppDir"]            = "程序目录",
            ["Loc_PortableEngine"]            = "引擎",
            ["Loc_PortableEngineMissing"]     = "未找到（桥接功能不可用）",
            ["Loc_PortablePrereq"]            = "驱动安装器",
            ["Loc_PortableDataDir"]           = "用户数据",
            ["Loc_PortableLicense"]           = "许可证",
            ["Loc_PortableLicenseMissing"]    = "缺失（GPL-3.0 要求随包分发）",
            ["Loc_PortablePresent"]           = "已就位",
            ["Loc_PortableMissing"]           = "缺失",
            ["Loc_PortableWritableNo"]        = "程序目录不可写 —— 放到用户可写的位置才能真正当绿色版用",

            // ── 设置页 · 控制器恢复状态 ──
            ["Loc_SectionRecovery"]           = "控制器恢复状态",
            ["Loc_RecoveryExplain"]           = "由引擎的 hidhide-watchdog 看门狗负责自动恢复；此处只呈现状态，并提供手动兜底。",
            ["Loc_RecoveryClean"]             = "干净：上次会话正常收尾，无残留标记",
            ["Loc_RecoveryActive"]            = "会话进行中（属主进程仍存活，属正常）",
            ["Loc_RecoveryPending"]           = "⚠ 检测到上次会话异常遗留，手柄可能仍对系统隐藏",
            ["Loc_RecoveryPendingDetail"]     = "原白名单 {0} 条 / 原黑名单 {1} 条",
            ["Loc_RecoveryRunOnce"]           = "下次登录兜底项：{0}",
            ["Loc_RecoveryRegistered"]        = "已登记",
            ["Loc_RecoveryNotRegistered"]     = "未登记",
            ["Loc_RecoveryUnreadable"]        = "无法判定：{0}",
            ["Loc_RecoveryRestore"]           = "恢复手柄可见性",
            ["Loc_Refresh"]                   = "刷新",
        };

    // ═══════════════════════════════════════════════════════════════
    //  English · 品牌名已从 ApexSenseBridge 替换为 Ds in Apex
    // ═══════════════════════════════════════════════════════════════
    public static readonly IReadOnlyDictionary<string, string> En =
        new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["Loc_AppName"]              = "Ds in Apex",
            ["Loc_AppSubtitle"]          = "DualSense \u2192 Flydigi APEX 4 / APEX 5 Bridge",
            ["Loc_AlreadyRunning"]       = "Ds in Apex is already running in the system tray.",
            ["Loc_StartupError"]         = "Startup error: ",
            ["Loc_Close"]                = "Close",
            ["Loc_BtnClose"]             = "Close",
            ["Loc_Hide"]                 = "Hide",
            ["Loc_Cancel"]               = "Cancel",
            ["Loc_Warning"]              = "Warning",
            ["Loc_Confirm"]              = "OK",

            ["Loc_TrayStatusStandby"]    = "Ds in Apex: Standby",
            ["Loc_TrayStatusActive"]     = "Ds in Apex: {0}",
            ["Loc_TrayTooltipStandby"]   = "Ds in Apex - Standby",
            ["Loc_TrayOpen"]             = "Open Interface...",
            ["Loc_TrayAutoDetect"]       = "Automatic Detection",
            ["Loc_TrayCheckUpdates"]     = "Check for Updates...",
            ["Loc_TrayControlPanel"]     = "Control Panel...",
            ["Loc_TrayLanguage"]         = "Language",
            ["Loc_TrayExit"]             = "Exit",
            ["Loc_NotificationActivated"] = "Ds in Apex activated",
            ["Loc_NotificationGameProfile"] = "{0}\nProfile: {1}",
            ["Loc_NotificationGame"]     = "Game",
            ["Loc_NotificationProfileStandard"] = "Standard",
            ["Loc_NotificationWarning"]  = "Ds in Apex \u2014 Warning",

            ["Loc_StatusBadgeStandby"]   = "\u25cf Standby",
            ["Loc_StatusBadgeActive"]    = "\u25cf Bridge active",
            ["Loc_NoActiveGame"]         = "No active game",
            ["Loc_WaitingHint"]          = "Waiting for a compatible game...",
            ["Loc_ProfileStandard"]      = "Standard",
            ["Loc_ProfileRemapping"]     = "Remapping active",
            ["Loc_PillTriggers"]         = "Triggers",
            ["Loc_PillHaptics"]          = "Haptics",
            ["Loc_BtnExcludeCurrent"]    = "Exclude this game",
            ["Loc_MsgExcluded"]          = "\u201c{0}\u201d has been excluded from automatic detection.",
            ["Loc_ManualBridgeGameTitle"] = "Forced manual bridge",

            ["Loc_SectionAutoDetect"]    = "Automatic Detection",
            ["Loc_EnableDetection"]      = "Enable detection",
            ["Loc_EnableDetectionHint"]  = "Activates the bridge when a compatible game is launched",
            ["Loc_LaunchCriteria"]       = "Launch the bridge only for:",
            ["Loc_CriteriaAdaptive"]     = "Games with adaptive triggers",
            ["Loc_CriteriaHaptic"]       = "Games with haptic feedback",

            ["Loc_SectionConfig"]        = "Configuration",
            ["Loc_Notifications"]        = "Notifications",
            ["Loc_NotificationsHint"]    = "Windows notification when the bridge is activated",
            ["Loc_ManualBridge"]         = "Force continuous activation",
            ["Loc_ManualBridgeHint"]     = "Keeps the bridge active continuously without waiting for a game",
            ["Loc_Language"]             = "Language",
            ["Loc_LanguageHint"]         = "User interface display language",
            ["Loc_SoftwareUpdate"]       = "Software update",
            ["Loc_BtnCheck"]             = "Check",

            ["Loc_UpdateBannerTitle"]    = "Update available!",
            ["Loc_UpdateBannerSubtitle"] = "A new version is ready for download",
            ["Loc_BtnDownload"]          = "Download",
            ["Loc_UpdateAvailableNotification"] = "Update available",
            ["Loc_UpdateAvailableBody"]  = "Ds in Apex v{0} is available.",
            ["Loc_UpdateDialogTitle"]    = "Ds in Apex \u2014 Updates",
            ["Loc_UpdateDialogAvailableTitle"] = "Ds in Apex \u2014 Update available",
            ["Loc_UpdatePrompt"]         = "A new version of Ds in Apex is available!\n\nCurrent version: v{0}\nLatest version: v{1}\n\nWould you like to download it now?",
            ["Loc_UpdateUpToDate"]       = "Ds in Apex is up to date (version v{0}).",
            ["Loc_UpdateError"]          = "Error checking for updates: ",
            ["Loc_UpdateCheckUnavailable"] = "Unable to check for updates at this time.\nPlease check your Internet connection.",

            ["Loc_DatabaseTitle"]        = "PCGamingWiki Database",
            ["Loc_CertifiedGamesSingular"] = "{0} certified game",
            ["Loc_CertifiedGamesPlural"] = "{0} certified games",
            ["Loc_BtnGameList"]          = "Game list",
            ["Loc_BtnLearnedExecutables"] = "Learned",
            ["Loc_BtnSync"]              = "Sync",
            ["Loc_Syncing"]              = "Synchronizing...",
            ["Loc_SyncSuccess"]          = "Update successful!\n{0} {1}.",
            ["Loc_SyncSuccessGamesSingular"] = "compatible game loaded",
            ["Loc_SyncSuccessGamesPlural"] = "compatible games loaded",
            ["Loc_SyncFailed"]           = "Unable to download the latest list.\nPlease check your Internet connection.",
            ["Loc_LearnedWindowTitle"]   = "Learned executables",
            ["Loc_LearnedWindowHint"]    = "Validated after the game process remains stable for 30 seconds, including passive identification during a forced manual bridge. Exports never include local paths.",
            ["Loc_LearnedGame"]          = "Game",
            ["Loc_LearnedExecutable"]    = "Executable",
            ["Loc_LearnedMethod"]        = "Detection method",
            ["Loc_LearnedSessions"]      = "Sessions",
            ["Loc_LearnedLastSeen"]      = "Last seen",
            ["Loc_LearnedEmpty"]         = "No executable has been learned yet.",
            ["Loc_LearnedCountSingular"] = "{0} learned executable",
            ["Loc_LearnedCountPlural"]   = "{0} learned executables",
            ["Loc_LearningPendingSingular"] = "{0} validation in progress",
            ["Loc_LearningPendingPlural"] = "{0} validations in progress",
            ["Loc_BtnSelectAll"]         = "Select all",
            ["Loc_BtnDeleteLearned"]     = "Delete",
            ["Loc_BtnExportLearned"]     = "Export",
            ["Loc_LearnedDeleteConfirm"] = "Delete the selected learned associations ({0})?",
            ["Loc_LearnedExportSuccess"] = "The selected associations were exported without local paths.",
            ["Loc_LearnedExportFailed"]  = "The export failed: {0}",

            ["Loc_FooterStatus"]         = "Ds in Apex running in background",
            ["Loc_BtnHide"]              = "Hide",

            ["Loc_GameListTitle"]        = "Ds in Apex \u2014 Compatible Games",
            ["Loc_GameListSubtitle"]     = "Browse certified games and manage automatic exclusions",
            ["Loc_SearchPlaceholder"]    = "Search a game...",
            ["Loc_TabAll"]               = "All",
            ["Loc_TabTriggers"]          = "Triggers",
            ["Loc_TabHaptics"]           = "Haptics",
            ["Loc_TabExcluded"]          = "Excluded",
            ["Loc_GamesDisplayedSingular"] = "{0} game displayed",
            ["Loc_GamesDisplayedPlural"] = "{0} games displayed",
            ["Loc_GamesExcludedSingular"] = "{0} excluded",
            ["Loc_GamesExcludedPlural"]  = "{0} excluded",
            ["Loc_PillAdaptive"]         = "Adaptive triggers",
            ["Loc_PillHaptic"]           = "Haptic feedback",
            ["Loc_PillTouchpad"]         = "Touchpad remapping",
            ["Loc_ApexProfile"]          = "APEX profile",
            ["Loc_ApexProfileKeep"]      = "Keep current",
            ["Loc_ApexProfileNumber"]    = "Profile {0}",
            ["Loc_ApexProfileHint"]      = "Temporarily selects this onboard profile while the game is running, then restores the previous profile.",
            ["Loc_StateIncluded"]        = "Included",
            ["Loc_StateExcluded"]        = "Excluded",
            ["Loc_ExclusionsSavedHint"]  = "Exclusions and game profiles are automatically saved.",
            ["Loc_NavCertifiedGames"]    = "Certified games",
            ["NavLearnedExecutables"]    = "Learned executables",
            ["Loc_NavLearnedExecutables"] = "Learned executables",
            ["Loc_LearnedSubtitle"]      = "Executables associated with compatible games on this PC",
            ["Loc_LearnedSearchPlaceholder"] = "Search executable or game...",
            ["Loc_LearnedEmptySubtitle"] = "When a game runs with a stable session, it will appear here for instant startup.",
            ["Loc_LearnedEmptyPendingSingular"] = "A game was detected. Keep playing while its executable is validated.",
            ["Loc_LearnedEmptyPendingPlural"] = "{0} game processes were detected. Keep playing while their executables are validated.",
            ["Loc_BtnDeleteSingle"]      = "Delete",

            ["Loc_NavDashboard"]         = "Dashboard",
            ["Loc_NavGameLibrary"]       = "Game Library",
            ["Loc_NavLearned"]           = "Learned",
            ["Loc_NavDrivers"]           = "Drivers",
            ["Loc_NavHardwareTest"]      = "Hardware Test",
            ["Loc_NavDiagnostics"]       = "Diagnostics",
            ["Loc_NavSettings"]          = "Settings",
            ["Loc_NavAbout"]             = "About",

            ["Loc_PageDashboardDesc"]    = "Bridge status, current game and quick actions",
            ["Loc_PageGameLibraryDesc"]  = "Browse certified games, manage exclusions and profile bindings",
            ["Loc_PageLearnedDesc"]      = "Recognized executables and their session history",
            ["Loc_PageDriversDesc"]      = "USBip / HidHide / ViGEmBus driver status and installation",
            ["Loc_PageHardwareDesc"]     = "Device identification, trigger and rumble tests, input monitor",
            ["Loc_PageDiagnosticsDesc"]  = "Collect diagnostics and export a report",
            ["Loc_PageSettingsDesc"]     = "Detection policy, notifications, language and updates",
            ["Loc_PageAboutDesc"]        = "Version info, open-source license and project notes",

            ["Loc_PlaceholderPending"]   = "This page will be implemented in a later phase.",

            ["Loc_None"]                     = "None",
            ["Loc_ErrBridgeIpcCollision"]    = "IPC event name collision.",
            ["Loc_ErrBridgeStartFailed"]     = "Unable to start the Ds in Apex bridge: ",
            ["Loc_ErrBridgeProcessNotStarted"] = "The bridge process did not start.",
            ["Loc_ErrBridgeStopFailed"]      = "Failed to stop the bridge session: ",
            ["Loc_ErrBridgeExited"]          = "The bridge exited before signalling ready (code {0}).",
            ["Loc_ErrBridgeInitTimeout"]     = "The bridge did not finish initializing within {0} seconds.",
            ["Loc_ErrBridgeIpcIncompatible"] = "The bridge returned an incompatible IPC status.",
            ["Loc_ErrBridgeInitFailed"]      = "Bridge initialization failed (code {0}).",
            ["Loc_ErrBridgeStartFailedShort"] = "The bridge failed to start.",
            ["Loc_ErrSessionAlreadyActive"]  = "A session is already active or initializing.",
            ["Loc_ErrExternalSessionActive"] = "A bridge session managed by Playnite or another application is already active.",
            ["Loc_ErrExternalSessionActiveHint"] = "This application will leave that session untouched.",
            ["Loc_ErrEngineNotFound"]        = "ApexSenseBridge.exe was not found. Please install or repair Ds in Apex.",
            ["Loc_LogStartingBridge"]        = "Starting bridge: {0} {1}",
            ["Loc_LogStoppingSession"]       = "Stopping session: {0}",

            ["Loc_PhaseEmpty"]               = "Idle",
            ["Loc_PhaseStarting"]            = "Starting",
            ["Loc_PhaseReady"]               = "Ready",
            ["Loc_PhaseStopping"]            = "Stopping",
            ["Loc_PhaseStopped"]             = "Stopped",
            ["Loc_PhaseFailed"]              = "Failed",

            ["Loc_SectionBridge"]            = "Bridge",
            ["Loc_QuickActions"]             = "Quick actions",
            ["Loc_BtnStartBridge"]           = "Start bridge",
            ["Loc_BtnStopBridge"]            = "Stop bridge",
            ["Loc_BtnOpenSettings"]          = "Open settings",
            ["Loc_BridgeState"]              = "State",
            ["Loc_BridgePid"]                = "Process ID",
            ["Loc_EnginePath"]               = "Engine path",
            ["Loc_EngineMissing"]            = "Engine executable not found",
            ["Loc_EngineRescan"]             = "Locate again",

            ["Loc_HapticThreshold"]          = "Haptic threshold",
            ["Loc_HapticThresholdHint"]      = "Audio haptics below this intensity are ignored (0-95)",
            ["Loc_InitTimeout"]              = "Initialization timeout",
            ["Loc_InitTimeoutHint"]          = "Seconds to wait for the bridge to become ready (5-120)",
            ["Loc_SectionAppearance"]        = "Appearance",
            ["Loc_Theme"]                    = "Theme",
            ["Loc_ThemeHint"]                = "Interface color scheme",
            ["Loc_ThemeSystem"]              = "Follow system",
            ["Loc_ThemeLight"]               = "Light",
            ["Loc_ThemeDark"]                = "Dark",
            ["Loc_AutoSaveHint"]             = "All setting changes are saved immediately.",

            // ── Game Library (P3) ──
            ["Loc_GamesSearchPlaceholder"]   = "Search title or profile...",
            ["Loc_GamesFilterAll"]           = "All games",
            ["Loc_GamesFilterAdaptive"]      = "Adaptive triggers only",
            ["Loc_GamesFilterHaptic"]        = "Haptics only",
            ["Loc_GamesFilterExcluded"]      = "Excluded",
            ["Loc_GamesSortTitle"]           = "Sort by title",
            ["Loc_GamesSortAppId"]           = "Sort by Steam AppID",
            ["Loc_GamesSyncCloud"]           = "Sync library",
            ["Loc_GamesSyncing"]             = "Syncing...",
            ["Loc_GamesSyncOk"]              = "Synced: {0} games",
            ["Loc_GamesSyncFail"]            = "Sync failed (local data kept)",
            ["Loc_GamesShown"]               = "{0} shown",
            ["Loc_GamesExcludedCount"]       = "{0} excluded",
            ["Loc_GamesExcludeToggle"]       = "Exclude",
            ["Loc_LegendAdaptive"]           = "Adaptive triggers",
            ["Loc_LegendHaptic"]             = "Haptic feedback",
            ["Loc_LegendRemap"]              = "Custom remap",
            ["Loc_ApexProfileKeep"]          = "Keep as is",
            ["Loc_ApexProfile1"]             = "APEX profile 1",
            ["Loc_ApexProfile2"]             = "APEX profile 2",
            ["Loc_ApexProfile3"]             = "APEX profile 3",
            ["Loc_ApexProfile4"]             = "APEX profile 4",

            // ── Learned Executables (P3) ──
            ["Loc_LearnedSearchPlaceholder"] = "Search title, executable or path...",
            ["Loc_LearnedCount"]             = "{0} learned record(s)",
            ["Loc_LearningPendingCount"]     = "{0} pending",
            ["Loc_LearnedEmpty"]             = "No learned records yet",
            ["Loc_LearnedEmptySubtitle"]     = "Once a game is detected and runs stably for about 30 seconds, the association appears here.",
            ["Loc_LearnedDeleteConfirm"]     = "Delete the selected {0} learned record(s)? This cannot be undone.",
            ["Loc_LearnedExportSuccess"]     = "Export completed.",
            ["Loc_LearnedExportFailed"]      = "Export failed: {0}",
            ["Loc_BtnSelectAll"]             = "Select all",
            ["Loc_BtnDeleteLearned"]         = "Delete",
            ["Loc_BtnExportLearned"]         = "Export",
            ["Loc_BtnDelete"]                = "Delete",

            // ── Driver Management (P4) ──
            ["Loc_Driver_usbip-win2"]        = "usbip-win2 driver (USB redirection)",
            ["Loc_Driver_HidHide"]           = "HidHide (controller hiding)",
            ["Loc_Driver_ViGEmBus"]          = "ViGEmBus (optional)",
            ["Loc_DriverState_Running"]      = "Ready",
            ["Loc_DriverState_Installed"]    = "Installed",
            ["Loc_DriverState_NotInstalled"] = "Not installed",
            ["Loc_DriverState_Outdated"]     = "Version mismatch",
            ["Loc_DriverState_Partial"]      = "Incomplete",
            ["Loc_DriverState_OptionalMissing"] = "Not installed (optional)",
            ["Loc_DriverState_Unknown"]      = "Unknown",
            ["Loc_DriverVersionExpected"]    = "Requires version {0}",
            ["Loc_DriverVersionInstalled"]   = "Installed version {0}",
            ["Loc_DriverServices"]           = "Services: {0}",
            ["Loc_DriverInstallerVerified"]  = "Bundled installer passed SHA-256 check",
            ["Loc_DriverInstallerUnverified"] = "Bundled installer failed its SHA-256 check",
            ["Loc_DriverInstallerMissing"]   = "Bundled installer not found",
            ["Loc_DriverInstallerNone"]      = "No bundled installer for this component",
            ["Loc_DriversSummary"]           = "{0} of {1} ready",
            ["Loc_DriversRefresh"]           = "Rescan",
            ["Loc_DriversInstall"]           = "Install",
            ["Loc_DriversRepair"]            = "Repair",
            ["Loc_DriversInstalling"]        = "Installing {0}... (confirm the UAC prompt if shown)",
            ["Loc_DriversInstallDone"]       = "Installation completed.",
            ["Loc_DriversElevated"]          = "Running with administrator rights.",
            ["Loc_DriversNotElevated"]       = "Install / repair requires administrator rights; a UAC prompt will appear.",
            ["Loc_DriversNeedsRestart"]      = "A driver is registered but not running yet; a Windows restart may be required.",
            ["Loc_DriversOptionalHint"]      = "Optional component: DIA ships an integrated libVIIPER, so it is not required.",

            // ═══════════════ P5: Hardware test + diagnostics ═══════════════
            // ── Connection ──
            ["Loc_Link_Wired"]               = "Wired",
            ["Loc_Link_Dongle"]              = "2.4 GHz dongle",
            ["Loc_Link_Bluetooth"]           = "Bluetooth",
            ["Loc_Link_Unknown"]             = "Unknown",

            // ── Short words ──
            ["Loc_HwYes"]                    = "Yes",
            ["Loc_HwNo"]                     = "No",
            ["Loc_HwNone"]                   = "None",
            ["Loc_HwCharging"]               = "charging",
            ["Loc_HwLatest"]                 = "latest",

            // ── Status bar ──
            ["Loc_HwEngineReady"]            = "Engine available",
            ["Loc_HwEngineMissing"]          = "Engine not found",
            ["Loc_HwSessionRunning"]         = "Bridge session running (hardware tests locked)",
            ["Loc_HwSessionIdle"]            = "No bridge session",
            ["Loc_HwRefresh"]                = "Re-detect device",
            ["Loc_HwBusyListing"]            = "Reading device information...",
            ["Loc_HwBusyRunning"]            = "Running {0}...",

            // ── Device card ──
            ["Loc_HwNoDevice"]               = "No controller detected",
            ["Loc_HwNoDeviceHint"]           = "Make sure the controller is connected in DInput mode (hold FN + A for about 3 seconds).",
            ["Loc_HwDeviceDetail"]           = "VID:PID {0}:{1} - input {2} bytes / output {3} bytes",
            ["Loc_HwIdentityDetail"]         = "Codename {0} - firmware {1} - {2}",
            ["Loc_HwLegacyAlias"]            = "{0} (engine reports: {1})",

            // ── Sections ──
            ["Loc_HwSectionReadOnly"]        = "Read-only checks",
            ["Loc_HwSectionReadOnlyHint"]    = "These commands only read device information and change nothing; run them at any time.",
            ["Loc_HwSectionInput"]           = "Input monitor",
            ["Loc_HwSectionInputHint"]       = "While sampling, move the sticks and press the triggers and buttons; the ranges actually read are shown afterwards.",
            ["Loc_HwSectionTest"]            = "Hardware tests (they really drive the controller)",
            ["Loc_HwSectionTestHint"]        = "The following actions physically drive a trigger or a motor - hold the controller first. Unavailable while a bridge session is running.",
            ["Loc_HwSessionBlocksTest"]      = "A bridge session is running: test commands contend for the same HID interface. Stop the bridge first.",
            ["Loc_HwSectionEmergency"]       = "Emergency actions",
            ["Loc_HwSectionEmergencyHint"]   = "For recovery from abnormal states. These change global state or affect sessions owned by other programs.",
            ["Loc_HwSampleSeconds"]          = "Sample seconds",
            ["Loc_HwRawOutput"]              = "Raw output",
            ["Loc_HwParseDegraded"]          = "Engine output did not match the expected format; showing raw text instead: {0}",
            ["Loc_HwConfirmTitle"]           = "Confirm",
            ["Loc_HwConfirmStopSessions"]    = "This stops every active bridge session, including ones started by the Playnite add-on or the official tray. Continue?",
            ["Loc_HwConfirmRestoreVisibility"] = "This restores the hidden controller's visibility and the APEX profile state. Continue?",

            // ── Buttons ──
            ["Loc_HwBtnDiagnose"]            = "HID interface diagnostics",
            ["Loc_HwBtnXInput"]              = "XInput slots",
            ["Loc_HwBtnDryRun"]              = "Packet preview",
            ["Loc_HwBtnVirtualDs"]           = "Virtual DS5 test",
            ["Loc_HwBtnInputMonitor"]        = "Start monitor",
            ["Loc_HwBtnTestRt"]              = "Right trigger test",
            ["Loc_HwBtnTestRumble"]          = "Rumble test",
            ["Loc_HwBtnPortTest"]            = "Full port test",
            ["Loc_HwBtnProfileSwitch"]       = "Profile switch test",
            ["Loc_HwBtnClear"]               = "Clear triggers and rumble",
            ["Loc_HwBtnStopSessions"]        = "Stop all sessions",
            ["Loc_HwBtnRestoreVisibility"]   = "Restore controller visibility",

            // ── Result titles ──
            ["Loc_HwResultIdentify"]         = "Device identity",
            ["Loc_HwResultDiagnose"]         = "HID interface diagnostics",
            ["Loc_HwResultInputStatus"]      = "Input monitor result",
            ["Loc_HwResultVirtualDs"]        = "Virtual DualSense result",
            ["Loc_HwResultXInput"]           = "XInput slots",
            ["Loc_HwResultDryRun"]           = "Test packet preview",
            ["Loc_HwResultTestRt"]           = "Right trigger test",
            ["Loc_HwResultTestRumble"]       = "Rumble test",
            ["Loc_HwResultProfileSwitch"]    = "Profile switch test",
            ["Loc_HwResultPortTest"]         = "Full port test",
            ["Loc_HwResultClear"]            = "Clear effects",
            ["Loc_HwResultStopSessions"]     = "Stop sessions",
            ["Loc_HwResultRestoreVisibility"] = "Restore controller visibility",

            // ── Result fields ──
            ["Loc_HwField_Conclusion"]       = "Result",
            ["Loc_HwField_InterfaceCount"]   = "HID interfaces",
            ["Loc_HwField_Apex4Interfaces"]  = "APEX 4 vendor interfaces",
            ["Loc_HwField_XInputSlots"]      = "Connected slots",
            ["Loc_HwField_Model"]            = "Model",
            ["Loc_HwField_Codename"]         = "Codename",
            ["Loc_HwField_DeviceType"]       = "Device type",
            ["Loc_HwField_Firmware"]         = "Firmware",
            ["Loc_HwField_Link"]             = "Connection",
            ["Loc_HwField_Battery"]          = "Battery",
            ["Loc_HwField_AdaptiveTriggers"] = "Adaptive triggers",
            ["Loc_HwField_Backend"]          = "Backend",
            ["Loc_HwField_EventDriven"]      = "Event driven",
            ["Loc_HwField_ReceivedState"]    = "Received state",
            ["Loc_HwField_Reports"]          = "Reports",
            ["Loc_HwField_StateChanges"]     = "State changes",
            ["Loc_HwField_Timeouts"]         = "Timeouts",
            ["Loc_HwField_ParseFailures"]    = "Parse failures",
            ["Loc_HwField_LeftStick"]        = "Left stick X, Y",
            ["Loc_HwField_RightStick"]       = "Right stick X, Y",
            ["Loc_HwField_Triggers"]         = "Triggers L2, R2",
            ["Loc_HwField_DPad"]             = "D-pad (last)",
            ["Loc_HwField_SeenDPad"]         = "D-pad (during sample)",
            ["Loc_HwField_Buttons"]          = "Buttons",
            ["Loc_HwField_Warning"]          = "Warning",
            ["Loc_HwField_VirtualConnected"] = "Virtual DS5 connected",
            ["Loc_HwField_BackendVersion"]   = "Backend version",
            ["Loc_HwField_DsFirmware"]       = "DS5 firmware",
            ["Loc_HwField_InputMode"]        = "Input mode",
            ["Loc_HwField_ApexRouting"]      = "APEX routing",
            ["Loc_HwField_OutputReports"]    = "Output reports",
            ["Loc_HwField_TriggerReports"]   = "Trigger reports",
            ["Loc_HwField_RumbleReports"]    = "Rumble reports",
            ["Loc_HwField_AudioHaptics"]     = "Audio haptics frames",
            ["Loc_HwField_MalformedFrames"]  = "Malformed frames",
            ["Loc_HwField_UnknownFrames"]    = "Unknown frames",

            // ── Success summaries ──
            ["Loc_HwSummary_List"]           = "Found {0} candidate device(s).",
            ["Loc_HwSummary_ListEmpty"]      = "No APEX 4/5 vendor HID interface was found.",
            ["Loc_HwSummary_Identify"]       = "{0} - firmware {1} - {2}",
            ["Loc_HwSummary_Diagnose"]       = "Enumerated {0} HID interfaces, {1} of them APEX 4 vendor interfaces.",
            ["Loc_HwSummary_InputStatus"]    = "During sampling: {0} reports, {1} state changes, {2} timeouts.",
            ["Loc_HwSummary_VirtualDs"]      = "Virtual DualSense created and receiving feedback (backend {0}).",
            ["Loc_HwSummary_XInput"]         = "Connected XInput slot(s): {0}",
            ["Loc_HwSummary_XInputNone"]     = "No XInput device was detected by the system.",
            ["Loc_HwSummary_TestRt"]         = "Right trigger test finished and the trigger was reset.",
            ["Loc_HwSummary_TestRumble"]     = "Rumble test finished and the motors were stopped.",
            ["Loc_HwSummary_ProfileSwitch"]  = "Profile switch test finished and the original profile was restored.",
            ["Loc_HwSummary_PortTest"]       = "Full port test finished.",
            ["Loc_HwSummary_Clear"]          = "LT / RT reset to Normal and grip rumble stopped.",
            ["Loc_HwSummary_DryRun"]         = "Test packet generated (no HID writes were performed).",
            ["Loc_HwSummary_StopSessions"]   = "All active sessions stopped; virtual input, controller visibility and profiles were cleaned up.",
            ["Loc_HwSummary_RestoreVisibility"] = "Controller visibility and APEX profile state were restored.",
            ["Loc_HwSummary_Generic"]        = "Command completed successfully.",

            // ── Blocking and errors ──
            ["Loc_HwUnknownCommand"]         = "Unknown command: {0}",
            ["Loc_HwBlockedBySession"]       = "A bridge session is running; test commands need exclusive access to the controller. Stop the bridge first.",
            ["Loc_HwTimedOut"]               = "Command timed out (over {0} seconds) and was aborted.",
            ["Loc_HwRetriedNotice"]          = "(the first attempt failed because the device was busy; retried once automatically)",

            // ── Engine exit-code meanings ──
            ["Loc_HwExit_Ok"]                = "Command completed successfully.",
            ["Loc_HwExit_NoDevice"]          = "No APEX 4/5 vendor HID interface was found - check that the controller is connected in DInput mode.",
            ["Loc_HwExit_IdentityFailed"]    = "Identity verification failed - the device may be claimed by Flydigi Space Station or similar software.",
            ["Loc_HwExit_InputStreamFailed"] = "The input stream failed - the controller may have disconnected during sampling.",
            ["Loc_HwExit_NoState"]           = "No input state was received during sampling.",
            ["Loc_HwExit_OpenFailed"]        = "Could not open the controller.",
            ["Loc_HwExit_WriteFailed"]       = "Writing the trigger effect failed.",
            ["Loc_HwExit_ResetFailed"]       = "Automatic reset after the test failed - set both triggers back to Normal in Flydigi Space Station.",
            ["Loc_HwExit_RumbleFailed"]      = "Writing or stopping rumble failed.",
            ["Loc_HwExit_Apex5Only"]         = "This command supports APEX 5 only; nothing was sent for the current model.",
            ["Loc_HwExit_Apex4Only"]         = "This command requires a verified APEX 4; the current model does not match.",
            ["Loc_HwExit_ProfilePreflight"]  = "The profile preflight check failed before any switch.",
            ["Loc_HwExit_ProfileSwitchUnverified"] = "The profile switch could not be verified, but the original profile was restored.",
            ["Loc_HwExit_ProfileRestoreFailed"] = "The original profile could not be restored - use the 'Restore controller visibility' emergency action, or switch back manually with the controller shortcut.",
            ["Loc_HwExit_ClearFailed"]       = "Clearing trigger / rumble effects failed.",
            ["Loc_HwExit_StopSessionsFailed"] = "Requesting the active session stop failed - a process with higher privileges may own it.",
            ["Loc_HwExit_RestoreVisibilityFailed"] = "Restoring controller visibility failed - administrator rights may be required.",
            ["Loc_HwExit_BadArguments"]      = "The engine rejected the arguments (bad spelling or out-of-range value).",
            ["Loc_HwExit_GenericFailure"]    = "Command failed (exit code {0}; see the raw output).",

            // ── Diagnostics page ──
            ["Loc_DiagCollecting"]           = "Collecting...",
            ["Loc_DiagSuccess"]              = "Diagnostic archive created",
            ["Loc_DiagFailed"]               = "Collection failed",
            ["Loc_DiagArchivePath"]          = "{0}",
            ["Loc_DiagPartialKept"]          = "Partial files were kept at: {0}",
            ["Loc_DiagOutputDir"]            = "Output directory",
            ["Loc_DiagOpenDir"]              = "Open folder",
            ["Loc_DiagSampleSeconds"]        = "XInput sample seconds",
            ["Loc_DiagSkipSample"]           = "Skip the interactive sample (slots are still enumerated)",
            ["Loc_DiagKeepWorking"]          = "Keep the uncompressed files (for troubleshooting)",
            ["Loc_DiagSafetyNote"]           = "Read-only collection: it installs no driver, changes no controller setting and sends no effect or output report. The report excludes user and computer names.",
            ["Loc_DiagBtnCollect"]           = "Collect diagnostics and export ZIP",
            ["Loc_DiagBtnCancel"]            = "Abort",
            ["Loc_DiagRevealArchive"]        = "Show in File Explorer",
            ["Loc_DiagWarningsTitle"]        = "The collection reported the following warnings:",
            ["Loc_DiagLog"]                  = "Collection log",
            ["Loc_DiagStep_system"]          = "System information",
            ["Loc_DiagStep_hid"]             = "HID interfaces",
            ["Loc_DiagStep_pnp"]             = "Plug and Play topology",
            ["Loc_DiagStep_xinput"]          = "XInput",
            ["Loc_DiagStep_software"]        = "Conflicting software",
            ["Loc_DiagStep_archive"]         = "Archive",

            // ══════════════ P6 · Tray background / autostart / portable / recovery ══════════════

            // ── Tray menu ──
            ["Loc_TrayStatusLabel"]           = "Status",
            ["Loc_TrayDiagnostics"]           = "Diagnostics...",
            ["Loc_TrayHardwareTest"]          = "Hardware test...",
            ["Loc_TrayStartWithWindows"]      = "Start with Windows",
            ["Loc_TrayPortableInfo"]          = "Portable info...",
            ["Loc_TrayRecoveryRestore"]       = "Restore controller visibility",
            ["Loc_TrayRecoveryPending"]       = "Warning: previous session left a recovery marker (click to restore)",

            // ── Tray balloon notifications (Shell_NotifyIcon, not Toast - see 5.6) ──
            ["Loc_NotifyBridgeStartedTitle"]  = "Bridge started",
            ["Loc_NotifyBridgeStartedBody"]   = "{0}\nProfile: {1}",
            ["Loc_NotifyBridgeStoppedTitle"]  = "Bridge stopped",
            ["Loc_NotifyBridgeStoppedBody"]   = "Reason: {0}",
            ["Loc_NotifyBridgeErrorTitle"]    = "Bridge error",
            ["Loc_NotifyMinimizedTitle"]      = "Still running in the background",
            ["Loc_NotifyMinimizedBody"]       = "The window was hidden to the tray; the bridge keeps working. Use the tray menu to exit.",
            ["Loc_NotifyUpdateTitle"]         = "Update available",
            ["Loc_NotifyUpdateBody"]          = "v{0} → v{1}",
            ["Loc_NotifyRecoveryTitle"]       = "Controller recovery notice",
            ["Loc_NotifyRecoveryBody"]        = "A recovery marker from the previous session is still present; the controller may still be hidden.",

            // ── Settings · Startup and background ──
            ["Loc_SectionStartup"]            = "Startup and background",
            ["Loc_StartWithWindows"]          = "Start with Windows",
            ["Loc_StartWithWindowsHint"]      = "Launch at sign-in and minimize to the tray (current-user registry only, no administrator needed)",
            ["Loc_StartWithWindowsStaleTitle"] = "Autostart path is stale",
            ["Loc_StartWithWindowsStale"]     = "The autostart entry points to a program in a different location, so this setting will not work. This is expected after moving a portable folder.",
            ["Loc_StartWithWindowsRepair"]    = "Repair to current path",
            ["Loc_StartWithWindowsUnreadable"] = "Could not read the autostart entry: {0}",
            ["Loc_CloseToTray"]               = "Hide to tray when closing the window",
            ["Loc_CloseToTrayHint"]           = "Closing the window keeps the app running so the bridge stays active; use Exit in the tray menu to quit",
            ["Loc_CheckUpdatesOnStartup"]     = "Check for updates at startup",
            ["Loc_CheckUpdatesOnStartupHint"] = "Silent check; you are only notified when a newer version exists",
            ["Loc_CheckNow"]                  = "Check now",
            ["Loc_UpdateNoRelease"]           = "No downloadable release yet (current v{0})",
            ["Loc_UpdatePortableHint"]        = "Portable upgrade: download the new folder and replace the old one - your data and settings are unaffected.",

            // ── Settings · Portable deployment ──
            ["Loc_PortableInfo"]              = "Portable deployment",
            ["Loc_PortableHint"]              = "Extract and run: no install entry, no system service. Uninstalling means deleting the folder (user data is kept separately).",
            ["Loc_PortableAppDir"]            = "Program folder",
            ["Loc_PortableEngine"]            = "Engine",
            ["Loc_PortableEngineMissing"]     = "not found (bridging unavailable)",
            ["Loc_PortablePrereq"]            = "Driver installers",
            ["Loc_PortableDataDir"]           = "User data",
            ["Loc_PortableLicense"]           = "License",
            ["Loc_PortableLicenseMissing"]    = "missing (GPL-3.0 requires shipping it)",
            ["Loc_PortablePresent"]           = "present",
            ["Loc_PortableMissing"]           = "missing",
            ["Loc_PortableWritableNo"]        = "The program folder is not writable - move it somewhere writable to use it as a true portable build",

            // ── Settings · Controller recovery state ──
            ["Loc_SectionRecovery"]           = "Controller recovery state",
            ["Loc_RecoveryExplain"]           = "Recovery is handled automatically by the engine's hidhide-watchdog; this panel only reports state and offers a manual fallback.",
            ["Loc_RecoveryClean"]             = "Clean: the previous session ended normally, no marker left behind",
            ["Loc_RecoveryActive"]            = "Session in progress (owner process is still alive - normal)",
            ["Loc_RecoveryPending"]           = "Warning: the previous session ended abnormally; the controller may still be hidden",
            ["Loc_RecoveryPendingDetail"]     = "Original whitelist {0} entries / blacklist {1} entries",
            ["Loc_RecoveryRunOnce"]           = "Next sign-in fallback: {0}",
            ["Loc_RecoveryRegistered"]        = "registered",
            ["Loc_RecoveryNotRegistered"]     = "not registered",
            ["Loc_RecoveryUnreadable"]        = "Cannot determine: {0}",
            ["Loc_RecoveryRestore"]           = "Restore controller visibility",
            ["Loc_Refresh"]                   = "Refresh",
        };
}
